services:
  openclaw:
    image: justlikemaki/openclaw-docker-cn-im:latest
    ports:
      - "18789:18789"
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      - API_KEY=123456
      - BASE_URL=http://host.docker.internal:3000/claude-kiro-oauth/v1
      - API_PROTOCOL=openai-completions
      - MODEL_ID=claude-opus-4-6
      - IMAGE_MODEL_ID=claude-sonnet-4-6
      - OPENCLAW_GATEWAY_TOKEN=123456
      - OPENCLAW_GATEWAY_PORT=18789
      - OPENCLAW_GATEWAY_BIND=lan
      - OPENCLAW_GATEWAY_DANGEROUSLY_DISABLE_DEVICE_AUTH=true
      - FEISHU_APP_ID=cli_a92d187342f91cb3
      - FEISHU_APP_SECRET=C4LL5JmPecNAGqb0ka9bsdaEYhKZUs8r
    volumes:
      - ~/.openclaw:/home/node/.openclaw
